#!/bin/sh
alert="ALERT!!!
"
tanggal=$(date "+%F %H:%M:%S")" 
"
lokasi="Nama UPS
"
mes="Shutting Down Display
"
 case $1 in
       onbatt)
          logger -t upssched-cmd "UPS running on battery"
          /usr/bin/wall "Shutdown in 60 seconds!"
          ;;
       earlyshutdown)
          logger -t upssched-cmd "UPS on battery too long, early shutdown"
          /sbin/upsmon -c fsd
          ;;
        shutdownnow)
          /usr/bin/wall "UPS has been on battery for 60 seconds. Shutting down NOW!"
          curl --data chat_id="-723095568" --data-urlencode "text=<b>${alert}</b><code>${tanggal}PLN OFF di ${lokasi}${mes}</code>" "https://api.telegram.org/bot5018630455:AAGtGqco1EKa4gNcyRJ-UKWvOnoGMKgeKHk/sendMessage?parse_mode=HTML"
          /sbin/upsmon -c fsd
        ;;
       shutdowncritical)
          logger -t upssched-cmd "UPS on battery critical, forced shutdown"
          /sbin/upsmon -c fsd
          ;;
       upsgone)
          logger -t upssched-cmd "UPS has been gone too long, can't reach"
          ;;
       *)
          logger -t upssched-cmd "Unrecognized command: $1"
          ;;
 esac
